name: Deploy container and Test the application

on:
  push:
    branches:
      - master

env:
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432
  POSTGRES_DB: live_coding_challenge
  POSTGRES_USER: api_access_user
  POSTGRES_PASSWORD: I_am_quite_a_strong_password!

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Start containers
      run: |
        docker-compose up -d
        echo "Waiting for containers to start..."
        sleep 10

    - name: Test Application
      run: |
        cd api
        npm ci
        npm test
        
